### ISSUE TITLE
Transfer to a fully-featured Grafana plugin?

### ISSUE THREAD

**Issue by sofixa** [wevanscfi/grafana-newrelic-apm-datasource#4]
Hi, very good work here!

Are you interested in making this a normal Grafana plugin included in its repos as per [here](https://grafana.net/resources/getting-started-with-plugins) ?

I might be able to give you a hand if you want.

Cheers!

**Comment by wevanscfi** [comment]
I am working on it. I needed to read up a bit about Grafana prefers their plugins done.
If you have any suggestions for anything else that needs to get done before publishing, let me know.
- [X] Correct dir layout and include src files
- [ ] Test coverage
- [x] Clean up styling of query builder

**Comment by wevanscfi** [comment]
Adding some additional Todo's
- [x] Add option to proxy requests through Grafana server's dataproxy. (Resolving security concerns for this may require updates on Grafana's end)
