### ISSUE TITLE
How do you get other metrics like browsers...?

### ISSUE THREAD

**Issue by neodani** [wevanscfi/grafana-newrelic-apm-datasource#9]
It's possible obtain metrics like "Average page load time"?

curl -X GET "https://api.newrelic.com/v2/applications/XXXXXX/metrics/data.json" -H "X-Api-Key:XXXXXXXXXXXXX" -i -d 'names[]=EndUser&values[]=average_response_time&summarize=true'

I think that only works calls to 
https://api.newrelic.com/v2/applications.json or https://api.newrelic.com/v2/servers.json

Isn't it?

When I put "EndUser" into NameSpace doesn't find anything.

Thank you

**Comment by wevanscfi** [comment]
This data-source currently only supports the APM and Server APIs.
